name: Project auto-testing
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  BashProjectTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bash project test
        run: | 
          curl -o test/test.sh -L https://raw.githubusercontent.com/exit-zero-academy/BashProject/main/test/test.sh
          sudo bash test/test.sh